### PR TITLE
sonarr: support additional param for wanted

### PR DESCRIPTION
**Pull request by ctalkington**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass.
- [ ] There is no commented out code in this PR.
- [ ] The code has been formatted (`make lint`)
- [x] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by ctalkington** [comment]
@tkdrob one more here. question have you tried Sonarr v2 api or focused on v3? I'm just working out forcing users to upgrade or if there's some way to mostly work with v2 api (no api version in path)

**Comment by tkdrob** [comment]
> @tkdrob one more here. question have you tried Sonarr v2 api or focused on v3? I'm just working out forcing users to upgrade or if there's some way to mostly work with v2 api (no api version in path)

No. I have not focused on v2. How different is it?

**Comment by ctalkington** [comment]
I know the some endpoints had things like automatic series or episode file inclusion which are now parameters in v3.

Honestly, Sonarr devs announced v2 EOL about a year ago so I'll likely just rip the bandaid now.

**Comment by ctalkington** [comment]
@tkdrob any chance to merge and release this weekend? Need these changes for my sonarr PR

**Comment by tkdrob** [comment]
Thanks!

**Pull request merged**
