### PR TITLE
Generate default values for mypy

### PR DESCRIPTION
**Pull request by tkdrob**
## Proposed change

Use `attr.ib` to generate default values to satisfy mypy.
A few items are not yet converted, mostly likely by my error in the test config
Lists of classes is the only thing I could not get working.

CC: @ctalkington Perhaps you have a solution?

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass.
- [x] There is no commented out code in this PR.
- [x] The code has been formatted (`make lint`)
- [x] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by ctalkington** [comment]
@tkdrob what mypy was failing?

**Comment by ctalkington** [comment]
I'm not sure that this change actually achieves much in its current state because according to https://www.attrs.org/en/stable/api.html#attr.ib

> Does not do anything unless the class is also decorated with [attr.s](https://www.attrs.org/en/stable/api.html#attr.s)!

> type –

> The type of the attribute. In Python 3.6 or greater, the preferred method to specify the type is using a variable annotation (see [PEP 526](https://www.python.org/dev/peps/pep-0526/)). This argument is provided for backward compatibility. Regardless of the approach used, the type will be stored on Attribute.type.
> 
> Please note that attrs doesn’t do anything with this metadata by itself. You can use it as part of your own code or for [static type checking](https://www.attrs.org/en/stable/types.html).

**Comment by tkdrob** [comment]
> @tkdrob what mypy was failing?

Not the mypy checks here. In writing Home Assistant integrations, mypy considers everything as optional. But for what I'm using it's always present. A typical error would be `Item "None" of "Optional[SystemStatus]" has no attribute "version"`

**Comment by ctalkington** [comment]
> > @tkdrob what mypy was failing?
> 
> Not the mypy checks here. In writing Home Assistant integrations, mypy considers everything as optional. But for what I'm using it's always present. A typical error would be `Item "None" of "Optional[SystemStatus]" has no attribute "version"`

ah I ran into that the other day with move to strict typing in rokuecp.  was much simpler in my case though. usually to fix the HA side if you check for None first it'll resolve that side but yah not ideal when it's almost always gonna be filled in this case.

**Comment by ctalkington** [comment]
@tkdrob do you have an HA PR or code somewhere I could see / play with?

**Comment by tkdrob** [comment]
https://github.com/tkdrob/core/tree/lidarr

**Comment by tkdrob** [comment]
I may just drop 3.8 if this solves my problem. HA dropped 3.8 already so I suppose no need to support 3.8.

**Comment by ctalkington** [comment]
> https://github.com/tkdrob/core/tree/lidarr

The example you had before about SystemStatus seems like would be due to the DataUpdateCoordinator setting type to SystemStatus | None.  I'll have to try cloning your code locally but I really don't know that you would need all this attr.ib stuff, has never came up in my dataclasses even with strict.

**Comment by ctalkington** [comment]
> I may just drop 3.8 if this solves my problem. HA dropped 3.8 already so I suppose no need to support 3.8.

I would just drop 3.8 honestly since main focus is HA right?

**Comment by ctalkington** [comment]
> > https://github.com/tkdrob/core/tree/lidarr
> 
> The example you had before about SystemStatus seems like would be due to the DataUpdateCoordinator setting type to SystemStatus | None. I'll have to try cloning your code locally but I really don't know that you would need all this attr.ib stuff, has never came up in my dataclasses even with strict.

I don't see any issues reported with mypy that would require the changes here.  it'll be easier to work through some of it you want to get to a point and make an HA PR. Just do draft and request review from me and I'll help iron out whatever gets flagged.

**Comment by tkdrob** [comment]
`freeSpace` is a better example. We know that we have it when we get a response from calling `diskspace` but mypy does not accept it without casting. This PR has mypy accept these values without casting.

**Comment by tkdrob** [comment]
bdraco said this is definitely not needed and is just papering over the issues. Closing

**Pull request closed without merging**
